class ApplicationController < ::ActionController::Base
  # include _RbsRailsPathHelpers
end

class BoardsController < ::ApplicationController
  @board: Board
  @boards: Board::ActiveRecord_Relation

  def index: () -> (Array[{ id: Integer, title: String }] | void)
  def show: (Integer id) -> void
  def new: () -> void
  def edit: (Integer id) -> void
  def create: (String title) -> ({ id: Integer, message: String } | Array[String] | void)
  def update: (Integer id, String title) -> ({ id: Integer, message: String } | Array[String] | void)
  def destroy: (Integer id) -> ({ message: String } | void)
end
